import { useEffect, useMemo, useRef, useState } from "react";
import { AlertCircle, Archive, Box, ChevronDown, ChevronRight, CircleUserRound, File, FileCode2, FileImage, Folder, FolderOpen, GitPullRequest, Hammer, Import, Layers3, LogOut, PackageOpen, Plus, Search, Settings2, ShieldCheck, Sparkles, Upload, Users, X } from "lucide-react";
import type { ImportReport, ProjectFile, ProjectSummary } from "@mona/shared";
import { ApiError, StudioApi } from "./api.js";
import { folderFilesToZip } from "./folderZip.js";
import { useStudio } from "./store.js";
import { LockedPixelEditor } from "./LockedPixelEditor.js";
import { ItemManager } from "./ItemManager.js";
import { CitManager } from "./CitManager.js";
import { BuildManager } from "./BuildManager.js";
import { CollaborationManager } from "./CollaborationManager.js";
import { ReviewManager } from "./ReviewManager.js";
import { AutoUpdater } from "./AutoUpdater.js";

const API_URL = localStorage.getItem("mona-studio-api") ?? "https://www.monacraft.net/studio-api";
const friendlyError = (error: unknown) => error instanceof ApiError || error instanceof Error ? error.message : "処理に失敗しました。";

function Brand({ compact = false }: { compact?: boolean }) {
  return <div className={`brand ${compact ? "compact" : ""}`}><div className="brand-mark"><Layers3 size={22} /></div>{!compact && <div><strong>Mona Resource Studio</strong><span>RESOURCE PACK WORKSPACE</span></div>}</div>;
}

function LoginView({ api }: { api: StudioApi }) {
  const setSession = useStudio((state) => state.setSession); const [username, setUsername] = useState(""); const [password, setPassword] = useState(""); const [server, setServer] = useState(API_URL); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); setError(""); try { localStorage.setItem("mona-studio-api", server.replace(/\/$/, "")); api.baseUrl = server.replace(/\/$/, ""); const session = await api.login(username, password); api.setTokens(session.accessToken, session.refreshToken); setSession(session.user, session.accessToken, session.refreshToken); } catch (reason) { setError(friendlyError(reason)); } finally { setBusy(false); } };
  return <main className="login-page">
    <section className="login-art"><Brand /><div className="login-copy"><span className="eyebrow"><Sparkles size={14} /> TEAM AUTHORING</span><h1>ひとつのパックを、<br />ひとつのチームで。</h1><p>テクスチャ、モデル、CIT、レビュー、ビルドを安全なワークスペースへ統合します。</p></div><div className="login-grid" aria-hidden="true" /></section>
    <section className="login-panel"><form className="login-card" onSubmit={submit}><div className="card-icon"><ShieldCheck /></div><h2>ワークスペースへログイン</h2><p>管理者から発行されたアカウントを使用してください。</p>
      <label>ユーザー名<input autoFocus autoComplete="username" value={username} onChange={(e) => setUsername(e.target.value)} placeholder="username" required /></label>
      <label>パスワード<input type="password" autoComplete="current-password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="••••••••••••" required /></label>
      <details><summary>接続先サーバー</summary><label>API URL<input value={server} onChange={(e) => setServer(e.target.value)} type="url" required /></label></details>
      {error && <div className="inline-error" role="alert"><AlertCircle size={16} />{error}</div>}
      <button className="primary wide" disabled={busy}>{busy ? "接続しています…" : "ログイン"}</button><small>認証情報はこの端末へ平文保存されません。</small>
    </form></section>
  </main>;
}

function Dashboard({ api }: { api: StudioApi }) {
  const user = useStudio((s) => s.user)!; const setProject = useStudio((s) => s.setProject); const logout = useStudio((s) => s.logout); const [projects, setProjects] = useState<ProjectSummary[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [showCreate, setShowCreate] = useState(false);
  const load = async () => { setLoading(true); setError(""); try { setProjects(await api.listProjects()); } catch (reason) { setError(friendlyError(reason)); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  return <main className="dashboard"><header className="topbar"><Brand /><div className="user-chip"><CircleUserRound size={18} /><span>{user.displayName}<small>@{user.username}</small></span><button aria-label="ログアウト" onClick={() => void api.logout().catch(() => undefined).finally(logout)}><LogOut size={17} /></button></div></header>
    <section className="dashboard-body"><div className="page-heading"><div><span className="eyebrow">WORKSPACES</span><h1>プロジェクト</h1><p>参加しているResource Packワークスペースを選択します。</p></div><button className="primary" onClick={() => setShowCreate(true)}><Plus size={17} />新規プロジェクト</button></div>
      {error && <div className="banner error"><AlertCircle size={18} />{error}<button onClick={() => void load()}>再試行</button></div>}
      <div className="project-grid">{loading ? <div className="empty-state">プロジェクトを読み込んでいます…</div> : projects.length === 0 ? <div className="empty-state"><PackageOpen size={38} /><h3>最初のプロジェクトを作成</h3><p>新規プロジェクトを作り、Resource PackをImportしてください。</p></div> : projects.map((project) => <button key={project.id} className="project-card" onClick={() => setProject(project)}><div className="project-icon"><Box /></div><div className="project-meta"><div><span className={`role role-${project.role}`}>{project.role}</span><span>MC {project.minecraftVersion}</span></div><h2>{project.name}</h2><p>{project.description || "説明はまだありません。"}</p><footer><span>{project.fileCount} files</span><span>{new Date(project.updatedAt).toLocaleString("ja-JP")}</span></footer></div></button>)}</div>
    </section>{showCreate && <CreateProject api={api} onClose={() => setShowCreate(false)} onCreated={(project) => { setProjects((items) => [project, ...items]); setShowCreate(false); setProject(project); }} />}</main>;
}

function CreateProject({ api, onClose, onCreated }: { api: StudioApi; onClose: () => void; onCreated: (project: ProjectSummary) => void }) {
  const [name, setName] = useState(""); const [description, setDescription] = useState(""); const [minecraftVersion, setMinecraftVersion] = useState("1.21.11"); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); setError(""); try { onCreated(await api.createProject({ name, description, minecraftVersion })); } catch (reason) { setError(friendlyError(reason)); setBusy(false); } };
  return <div className="modal-backdrop" role="presentation" onMouseDown={(e) => e.target === e.currentTarget && onClose()}><form className="modal" onSubmit={submit}><header><div><span className="eyebrow">NEW WORKSPACE</span><h2>プロジェクトを作成</h2></div><button type="button" className="icon-button" onClick={onClose}><X /></button></header><label>プロジェクト名<input value={name} onChange={(e) => setName(e.target.value)} maxLength={80} required autoFocus placeholder="MONAKA Main Pack" /></label><label>説明<textarea value={description} onChange={(e) => setDescription(e.target.value)} maxLength={2000} rows={3} placeholder="チームで共有する目的や対象を書きます。" /></label><label>Minecraft Version<select value={minecraftVersion} onChange={(e) => setMinecraftVersion(e.target.value)}><option>1.21.11</option><option>1.21.10</option><option>1.21.9</option><option>1.21.8</option><option>1.21.7</option><option>1.21.6</option><option>1.21.5</option><option>1.21.4</option></select></label>{error && <div className="inline-error"><AlertCircle size={16} />{error}</div>}<footer><button type="button" className="secondary" onClick={onClose}>キャンセル</button><button className="primary" disabled={busy}>{busy ? "作成中…" : "作成"}</button></footer></form></div>;
}

function AddPngDialog({ file, defaultPath, onClose, onAdd }: { file: File; defaultPath: string; onClose: () => void; onAdd: (path: string) => Promise<void> }) {
  const [path, setPath] = useState(defaultPath); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); setError(""); try { await onAdd(path.trim().replaceAll("\\", "/")); } catch (reason) { setError(friendlyError(reason)); setBusy(false); } };
  return <div className="modal-backdrop" role="presentation" onMouseDown={(event) => event.target === event.currentTarget && !busy && onClose()}><form className="modal" onSubmit={submit}><header><div><span className="eyebrow">ADD TEXTURE</span><h2>PNG画像を追加</h2></div><button type="button" className="icon-button" disabled={busy} onClick={onClose}><X /></button></header><p className="modal-note">{file.name} · {file.size.toLocaleString()} bytes</p><label>Resource Pack内の追加先<input autoFocus value={path} onChange={(event) => setPath(event.target.value)} required pattern=".*\\.png" placeholder="assets/minecraft/textures/item/example.png" /></label><small className="field-help">例: assets/namespace/textures/item/example.png</small>{error && <div className="inline-error"><AlertCircle size={16} />{error}</div>}<footer><button type="button" className="secondary" disabled={busy} onClick={onClose}>キャンセル</button><button className="primary" disabled={busy || !path.trim().toLowerCase().endsWith(".png")}>{busy ? "追加中…" : "追加"}</button></footer></form></div>;
}

function defaultPngPath(tree: ProjectFile[], filename: string): string {
  const paths: string[] = []; const visit = (nodes: ProjectFile[]) => nodes.forEach((node) => { if (node.kind === "file") paths.push(node.path); else if (node.children) visit(node.children); }); visit(tree);
  const namespace = paths.map((path) => path.match(/^assets\/([^/]+)\//)?.[1]).find(Boolean) ?? "minecraft";
  const safeName = filename.toLocaleLowerCase("en-US").replace(/\.png$/i, "").replace(/[^a-z0-9_.-]+/g, "_").replace(/^_+|_+$/g, "") || "texture";
  return `assets/${namespace}/textures/item/${safeName}.png`;
}

function ExplorerNode({ node, depth, selected, onSelect }: { node: ProjectFile; depth: number; selected: string; onSelect: (node: ProjectFile) => void }) {
  const [open, setOpen] = useState(depth < 2); const folder = node.kind === "directory"; const Icon = folder ? (open ? FolderOpen : Folder) : node.mimeType === "image/png" ? FileImage : node.mimeType?.includes("json") ? FileCode2 : File;
  return <div><button className={`tree-row ${selected === node.path ? "selected" : ""}`} style={{ paddingLeft: 10 + depth * 14 }} onClick={() => folder ? setOpen((value) => !value) : onSelect(node)}>{folder ? (open ? <ChevronDown size={13} /> : <ChevronRight size={13} />) : <span className="tree-spacer" />}<Icon size={15} /><span>{node.name}</span></button>{folder && open && node.children?.map((child) => <ExplorerNode key={child.path} node={child} depth={depth + 1} selected={selected} onSelect={onSelect} />)}</div>;
}

function CommandPalette({ onClose, onPng, onZip, onFolder, onBack, canWrite }: { onClose: () => void; onPng: () => void; onZip: () => void; onFolder: () => void; onBack: () => void; canWrite: boolean }) {
  const [query, setQuery] = useState("");
  const commands = [
    ...(canWrite ? [{ label: "Texture: PNG画像を追加", hint: "Create", icon: FileImage, run: onPng }] : []),
    { label: "Resource Pack: ZIPをImport", hint: "Import", icon: Upload, run: onZip },
    { label: "Resource Pack: フォルダをImport", hint: "Import", icon: FolderOpen, run: onFolder },
    { label: "Project: Dashboardへ戻る", hint: "Navigation", icon: Archive, run: onBack },
  ].filter((command) => command.label.toLocaleLowerCase("ja").includes(query.toLocaleLowerCase("ja")));
  return <div className="palette-backdrop" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><div className="command-palette" role="dialog" aria-label="Command Palette"><div className="palette-search"><Search size={18} /><input autoFocus value={query} onChange={(event) => setQuery(event.target.value)} placeholder="コマンドを入力…" onKeyDown={(event) => event.key === "Escape" && onClose()} /></div><div className="palette-results">{commands.map((command, index) => { const Icon = command.icon; return <button key={command.label} autoFocus={index === 0 && query.length > 0} onClick={() => { command.run(); onClose(); }}><Icon size={16} /><span>{command.label}</span><small>{command.hint}</small></button>; })}{commands.length === 0 && <div className="palette-empty">一致するコマンドはありません。</div>}</div><footer><span><kbd>Tab</kbd> 選択</span><span><kbd>Enter</kbd> 実行</span><span><kbd>Esc</kbd> 閉じる</span></footer></div></div>;
}

function Studio({ api }: { api: StudioApi }) {
  const project = useStudio((s) => s.activeProject)!; const user = useStudio((s) => s.user)!; const setProject = useStudio((s) => s.setProject); const problems = useStudio((s) => s.problems); const setProblems = useStudio((s) => s.setProblems); const [tree, setTree] = useState<ProjectFile[]>([]); const [selected, setSelected] = useState<ProjectFile | null>(null); const [preview, setPreview] = useState<{ url?: string; blob?: Blob; text?: string; type: "empty" | "image" | "text" | "binary" }>({ type: "empty" }); const [workspaceView, setWorkspaceView] = useState<"explorer" | "items" | "cit" | "build" | "collaboration" | "review">("explorer"); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [palette, setPalette] = useState(false); const [pendingImage, setPendingImage] = useState<File | null>(null); const zipInput = useRef<HTMLInputElement>(null); const folderInput = useRef<HTMLInputElement>(null); const imageInput = useRef<HTMLInputElement>(null); const canWrite = ["owner", "admin", "manager", "editor"].includes(project.role);
  const loadTree = async () => { try { setTree((await api.files(project.id)).tree); } catch (reason) { setError(friendlyError(reason)); } };
  useEffect(() => { void loadTree(); }, [project.id]);
  useEffect(() => { let closed = false; let disconnect: (() => void) | undefined; void api.connectRealtime(project.id, (event) => { window.dispatchEvent(new CustomEvent("mona-resource-realtime", { detail: event })); if (["file.created", "file.saved", "pack.imported", "cit.saved"].includes(event.type)) void loadTree(); }).then((close) => { if (closed) close(); else disconnect = close; }).catch((reason) => setError(friendlyError(reason))); return () => { closed = true; disconnect?.(); }; }, [api, project.id]);
  useEffect(() => () => { if (preview.url) URL.revokeObjectURL(preview.url); }, [preview.url]);
  const openFile = async (node: ProjectFile) => { setSelected(node); setError(""); try { const blob = await api.content(project.id, node.path); if (preview.url) URL.revokeObjectURL(preview.url); if (node.mimeType === "image/png") setPreview({ type: "image", blob }); else if (node.mimeType?.includes("json") || node.mimeType?.startsWith("text/")) { let text = await blob.text(); if (node.mimeType.includes("json")) try { text = JSON.stringify(JSON.parse(text), null, 2); } catch { /* show raw */ } setPreview({ type: "text", text }); } else setPreview({ type: "binary" }); } catch (reason) { setError(friendlyError(reason)); } };
  const runImport = async (file: File) => { setBusy(true); setError(""); try { const report: ImportReport = await api.importZip(project.id, file); setProblems(report.problems); await loadTree(); } catch (reason) { setError(friendlyError(reason)); } finally { setBusy(false); if (zipInput.current) zipInput.current.value = ""; if (folderInput.current) folderInput.current.value = ""; } };
  const chooseFolder = async (files: FileList | null) => { if (!files?.length) return; try { await runImport(await folderFilesToZip(files)); } catch (reason) { setError(friendlyError(reason)); } };
  const chooseImage = (file?: File) => { if (!file) return; if (!file.name.toLowerCase().endsWith(".png")) { setError("追加できる画像はPNGのみです。"); return; } if (file.size > 5 * 1024 * 1024) { setError("追加できるPNGは5MiBまでです。"); return; } setError(""); setPendingImage(file); if (imageInput.current) imageInput.current.value = ""; };
  const addImage = async (file: File, path: string) => { const created = await api.createFile(project.id, path, file); setPendingImage(null); await loadTree(); setWorkspaceView("explorer"); await openFile({ path: created.path, name: created.path.split("/").pop() ?? created.path, kind: "file", size: created.size, mimeType: created.mimeType, version: created.version }); };
  useEffect(() => { folderInput.current?.setAttribute("webkitdirectory", ""); folderInput.current?.setAttribute("directory", ""); }, []);
  useEffect(() => { const listener = (event: KeyboardEvent) => { if ((event.ctrlKey || event.metaKey) && event.shiftKey && event.key.toLocaleLowerCase() === "p") { event.preventDefault(); setPalette((value) => !value); } if (event.key === "Escape") setPalette(false); }; window.addEventListener("keydown", listener); return () => window.removeEventListener("keydown", listener); }, []);
  return <main className="studio"><header className="studio-topbar"><button className="back-brand" onClick={() => setProject(null)}><Brand compact /><span>{project.name}<small>MC {project.minecraftVersion} · {project.role}</small></span></button><nav>{canWrite && <button className="tool-button" onClick={() => imageInput.current?.click()} disabled={busy}><FileImage size={16} />PNG追加</button>}<button className="tool-button" onClick={() => zipInput.current?.click()} disabled={busy}><Upload size={16} />{busy ? "Import中…" : "ZIP Import"}</button><button className="tool-button" onClick={() => folderInput.current?.click()} disabled={busy}><FolderOpen size={16} />Folder Import</button><button className="icon-button" aria-label="設定"><Settings2 /></button></nav><input ref={imageInput} hidden type="file" accept=".png,image/png" onChange={(event) => chooseImage(event.target.files?.[0])} /><input ref={zipInput} hidden type="file" accept=".zip,application/zip" onChange={(e) => e.target.files?.[0] && void runImport(e.target.files[0])} /><input ref={folderInput} hidden type="file" multiple onChange={(e) => void chooseFolder(e.target.files)} /></header>
    <div className="workbench"><aside className="activity-bar"><button className={workspaceView === "explorer" ? "active" : ""} title="Explorer" onClick={() => setWorkspaceView("explorer")}><Archive /></button><button title="検索"><Search /></button><button className={workspaceView === "items" ? "active" : ""} title="Items" onClick={() => setWorkspaceView("items")}><Box /></button><button className={workspaceView === "cit" ? "active" : ""} title="CIT" onClick={() => setWorkspaceView("cit")}><Sparkles /></button><button className={workspaceView === "build" ? "active" : ""} title="Build" onClick={() => setWorkspaceView("build")}><Hammer /></button><button className={workspaceView === "collaboration" ? "active" : ""} title="Collaboration" onClick={() => setWorkspaceView("collaboration")}><Users /></button><button className={workspaceView === "review" ? "active" : ""} title="Review & Release" onClick={() => setWorkspaceView("review")}><GitPullRequest /></button></aside><aside className="explorer"><header><span>{workspaceView === "explorer" ? "EXPLORER" : workspaceView === "items" ? "ITEM MANAGER" : workspaceView === "cit" ? "CIT WORKSPACE" : workspaceView === "build" ? "BUILD PIPELINE" : workspaceView === "review" ? "REVIEW & RELEASE" : "COLLABORATION"}</span>{workspaceView === "explorer" && <button title="Import" onClick={() => zipInput.current?.click()}><Import size={14} /></button>}</header><div className="project-label">{project.name.toUpperCase()}</div><div className="tree">{workspaceView === "explorer" ? (tree.length ? tree.map((node) => <ExplorerNode key={node.path} node={node} depth={0} selected={selected?.path ?? ""} onSelect={(node) => void openFile(node)} />) : <div className="tree-empty"><PackageOpen /><span>Packは空です</span><button onClick={() => zipInput.current?.click()}>Importする</button></div>) : <div className="tree-empty">{workspaceView === "items" ? <Box /> : workspaceView === "cit" ? <Sparkles /> : workspaceView === "build" ? <Hammer /> : workspaceView === "review" ? <GitPullRequest /> : <Users />}<span>{workspaceView === "items" ? "Logical Item、カテゴリ、参照を中央のManagerで編集します。" : workspaceView === "cit" ? "CITルール、条件、参照、生成JSONを中央のEditorで管理します。" : workspaceView === "build" ? "Snapshot、Build進捗、ログ、成果物を中央のPipelineで管理します。" : workspaceView === "review" ? "Snapshot差分の承認と不変Releaseの公開を管理します。" : "Onlineメンバー、Lock、コメント、Activity、通知を管理します。"}</span></div>}</div></aside>
      <section className="editor"><div className="tabbar">{workspaceView === "items" ? <div className="tab active"><Box size={14} />Logical Items</div> : workspaceView === "cit" ? <div className="tab active"><Sparkles size={14} />Variants-CIT</div> : workspaceView === "build" ? <div className="tab active"><Hammer size={14} />Build &amp; Snapshots</div> : workspaceView === "collaboration" ? <div className="tab active"><Users size={14} />Collaboration</div> : workspaceView === "review" ? <div className="tab active"><GitPullRequest size={14} />Review &amp; Release</div> : selected ? <div className="tab active">{selected.mimeType === "image/png" ? <FileImage size={14} /> : <FileCode2 size={14} />}{selected.name}<span className="dirty-dot" /></div> : <div className="tab muted">Welcome</div>}</div><div className="editor-content">{workspaceView === "items" ? <ItemManager api={api} projectId={project.id} /> : workspaceView === "cit" ? <CitManager api={api} projectId={project.id} minecraftVersion={project.minecraftVersion} onProblems={setProblems} onChanged={loadTree} /> : workspaceView === "build" ? <BuildManager api={api} projectId={project.id} canBuild={["owner", "admin", "manager"].includes(project.role)} onRolledBack={loadTree} /> : workspaceView === "collaboration" ? <CollaborationManager api={api} projectId={project.id} role={project.role} selectedPath={selected?.path} /> : workspaceView === "review" ? <ReviewManager api={api} projectId={project.id} role={project.role} userId={user.id} /> : preview.type === "empty" ? <div className="welcome"><div className="welcome-logo"><Layers3 /></div><h1>Mona Resource Studio</h1><p>Explorerからファイルを選択するか、Resource PackをImportしてください。</p><div className="shortcut-list"><span>ZIPをImport</span><kbd>Toolbar</kbd><span>Command Palette</span><kbd>Ctrl Shift P</kbd><span>保存</span><kbd>Ctrl S</kbd></div></div> : preview.type === "image" && preview.blob && selected ? <LockedPixelEditor key={`${selected.path}:${selected.version ?? 1}`} api={api} projectId={project.id} file={selected} blob={preview.blob} canWrite={["owner", "admin", "manager", "editor"].includes(project.role)} onSaved={loadTree} /> : preview.type === "text" ? <pre className="code-preview"><code>{preview.text}</code></pre> : <div className="welcome"><File size={42} /><h2>プレビュー非対応</h2><p>このバイナリ形式はプレビュー対象外です。</p></div>}</div></section>
      <aside className="inspector"><header>INSPECTOR</header>{selected ? <div className="inspector-content"><span className="eyebrow">FILE</span><h3>{selected.name}</h3><dl><dt>Path</dt><dd>{selected.path}</dd><dt>Version</dt><dd>{selected.version ?? 1}</dd><dt>Size</dt><dd>{selected.size.toLocaleString()} bytes</dd><dt>MIME</dt><dd>{selected.mimeType ?? "binary"}</dd></dl></div> : <div className="inspector-empty">ファイルを選択すると詳細を表示します。</div>}</aside>
      <section className="problems"><header><button className="active">PROBLEMS <span>{problems.length}</span></button><button>OUTPUT</button><button>ACTIVITY</button></header><div className="problem-list">{error && <div className="problem error"><AlertCircle size={15} /><span>{error}</span></div>}{problems.length === 0 && !error ? <div className="no-problems"><ShieldCheck size={15} />検出された問題はありません。</div> : problems.map((problem, index) => <div className={`problem ${problem.severity}`} key={`${problem.code}-${index}`}><AlertCircle size={15} /><span><strong>{problem.code}</strong> {problem.message}</span><code>{problem.path}</code></div>)}</div></section></div>
    {pendingImage && <AddPngDialog key={`${pendingImage.name}:${pendingImage.lastModified}`} file={pendingImage} defaultPath={defaultPngPath(tree, pendingImage.name)} onClose={() => setPendingImage(null)} onAdd={(path) => addImage(pendingImage, path)} />}
    {palette && <CommandPalette onClose={() => setPalette(false)} onPng={() => imageInput.current?.click()} onZip={() => zipInput.current?.click()} onFolder={() => folderInput.current?.click()} onBack={() => setProject(null)} canWrite={canWrite} />}
    <footer className="statusbar"><span><ShieldCheck size={13} /> {project.role}</span><span>UTF-8</span><span>Spaces: 2</span><span className="status-spacer" /><button onClick={() => setPalette(true)}>Ctrl Shift P</button><span>API connected</span><span>MC {project.minecraftVersion}</span></footer>
  </main>;
}

export function App() {
  const accessToken = useStudio((state) => state.accessToken); const refreshToken = useStudio((state) => state.refreshToken); const user = useStudio((state) => state.user); const project = useStudio((state) => state.activeProject);
  const api = useMemo(() => new StudioApi(API_URL, "", (nextAccess, nextRefresh) => useStudio.getState().updateTokens(nextAccess, nextRefresh)), []); useEffect(() => api.setTokens(accessToken, refreshToken), [api, accessToken, refreshToken]);
  return <><AutoUpdater />{!user ? <LoginView api={api} /> : !project ? <Dashboard api={api} /> : <Studio api={api} />}</>;
}
