import { useEffect, useState } from "react";
import { AlertCircle, ArchiveRestore, Box, CheckCircle2, Clock3, Download, Hammer, History, LoaderCircle, Plus, RotateCcw, XCircle } from "lucide-react";
import type { BuildRecord, SnapshotRecord, StudioApi } from "./api.js";

const messageOf = (error: unknown) => error instanceof Error ? error.message : "処理に失敗しました。";
const statusIcon = (status: BuildRecord["status"]) => status === "succeeded" ? <CheckCircle2 /> : status === "failed" ? <XCircle /> : status === "running" ? <LoaderCircle className="spin" /> : <Clock3 />;
const date = (value: string) => new Date(value).toLocaleString("ja-JP");

export function BuildManager({ api, projectId, canBuild, onRolledBack }: { api: StudioApi; projectId: string; canBuild: boolean; onRolledBack: () => Promise<void> }) {
  const [builds, setBuilds] = useState<BuildRecord[]>([]); const [snapshots, setSnapshots] = useState<SnapshotRecord[]>([]); const [selected, setSelected] = useState<BuildRecord | null>(null); const [profile, setProfile] = useState<"development" | "release">("development"); const [label, setLabel] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const load = async () => { try { const [nextBuilds, nextSnapshots] = await Promise.all([api.listBuilds(projectId), api.listSnapshots(projectId)]); setBuilds(nextBuilds); setSnapshots(nextSnapshots); if (selected) { const match = nextBuilds.find((item) => item.id === selected.id); if (match) setSelected(await api.buildDetail(projectId, match.id)); } } catch (reason) { setError(messageOf(reason)); } };
  useEffect(() => { void load(); }, [projectId]);
  useEffect(() => { if (!builds.some((item) => item.status === "queued" || item.status === "running")) return; const timer = window.setInterval(() => void load(), 2000); return () => window.clearInterval(timer); }, [builds.map((item) => `${item.id}:${item.status}:${item.progress}`).join("|")]);
  const run = async () => { setBusy(true); setError(""); setNotice(""); try { const created = await api.startBuild(projectId, profile); setSelected(created); setNotice("Snapshotを固定し、Build Queueへ追加しました。"); await load(); } catch (reason) { setError(messageOf(reason)); } finally { setBusy(false); } };
  const createSnapshot = async () => { if (!label.trim()) return; setBusy(true); setError(""); try { await api.createSnapshot(projectId, label.trim()); setLabel(""); setNotice("Snapshotを作成しました。"); await load(); } catch (reason) { setError(messageOf(reason)); } finally { setBusy(false); } };
  const rollback = async (snapshot: SnapshotRecord) => { if (!window.confirm(`「${snapshot.label}」へRollbackします。現在の作業ツリーは置き換えられます。`)) return; setBusy(true); setError(""); try { const result = await api.rollbackSnapshot(projectId, snapshot.id); setNotice(`${result.restoredFiles} filesを復元しました。`); await onRolledBack(); await load(); } catch (reason) { setError(messageOf(reason)); } finally { setBusy(false); } };
  const inspect = async (build: BuildRecord) => { setError(""); try { setSelected(await api.buildDetail(projectId, build.id)); } catch (reason) { setError(messageOf(reason)); } };
  const download = async (build: BuildRecord) => { try { const blob = await api.buildArtifact(projectId, build.id); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `resource-pack-${build.id}.zip`; anchor.click(); URL.revokeObjectURL(url); } catch (reason) { setError(messageOf(reason)); } };
  return <div className="build-manager"><header><div><span className="eyebrow">IMMUTABLE PIPELINE</span><h2>Build &amp; Snapshots</h2><p>現在の編集内容を固定し、隔離WorkerでPackSquashを実行します。</p></div><div className="build-run"><select disabled={!canBuild} value={profile} onChange={(event) => setProfile(event.target.value as typeof profile)}><option value="development">Development</option><option value="release">Release</option></select><button className="primary" disabled={!canBuild || busy} onClick={() => void run()}><Hammer />{busy ? "処理中…" : "Build current"}</button></div></header>
    {(error || notice) && <div className={`build-banner ${error ? "error" : "success"}`}>{error ? <AlertCircle /> : <CheckCircle2 />}<span>{error || notice}</span></div>}
    {!canBuild && <div className="build-banner"><AlertCircle /><span>このRoleでは履歴の閲覧とArtifactの取得のみ可能です。</span></div>}
    <div className="build-columns"><section className="build-panel"><header><span><Hammer />BUILD JOBS</span><small>{builds.length}</small></header><div className="build-list">{builds.length === 0 ? <div className="build-empty"><Box />Build履歴はありません。</div> : builds.map((build) => <button key={build.id} className={selected?.id === build.id ? "active" : ""} onClick={() => void inspect(build)}><span className={`build-state ${build.status}`}>{statusIcon(build.status)}</span><span><strong>{build.snapshotLabel}</strong><small>{build.profile} · {date(build.createdAt)}</small><i><b style={{ width: `${build.progress}%` }} /></i></span><em>{build.progress}%</em></button>)}</div></section>
      <section className="build-panel snapshots"><header><span><History />SNAPSHOTS</span><small>{snapshots.length}</small></header><div className="snapshot-create"><input disabled={!canBuild} value={label} onChange={(event) => setLabel(event.target.value)} placeholder="Snapshot label" maxLength={120} /><button disabled={!canBuild || busy || !label.trim()} onClick={() => void createSnapshot()} title="Snapshotを作成"><Plus /></button></div><div className="snapshot-list">{snapshots.length === 0 ? <div className="build-empty"><ArchiveRestore />Snapshotはありません。</div> : snapshots.map((snapshot) => <article key={snapshot.id}><span><strong>{snapshot.label}</strong><small>{snapshot.manifest.files.length} files · {date(snapshot.createdAt)}</small><small>by {snapshot.createdBy}</small></span><button disabled={!canBuild || busy} onClick={() => void rollback(snapshot)} title="このSnapshotへRollback"><RotateCcw /></button></article>)}</div></section></div>
    <section className="build-output"><header><span>OUTPUT</span>{selected?.status === "succeeded" && <button onClick={() => void download(selected)}><Download />Artifactをダウンロード</button>}</header>{selected ? <><div className="build-summary"><span>Status <strong className={selected.status}>{selected.status}</strong></span><span>Profile <strong>{selected.profile}</strong></span><span>SHA-256 <code>{selected.artifactSha256 ?? "—"}</code></span><span>Size <strong>{selected.artifactSize ? `${Number(selected.artifactSize).toLocaleString()} bytes` : "—"}</strong></span></div><pre>{selected.log || (selected.status === "queued" ? "Workerの開始を待っています…" : "ログを取得しています…")}</pre></> : <div className="build-empty">Buildを選択すると進捗とログを表示します。</div>}</section>
  </div>;
}
