import { useEffect, useState } from "react";
import { Activity, AlertCircle, Bell, Check, Circle, FileText, LockKeyhole, MessageSquare, Plus, RefreshCw, Trash2, Users } from "lucide-react";
import type { ActivityEntry, FileLock, LogicalItem, PresenceUser, ProjectComment, ProjectMember, StudioApi, StudioNotification } from "./api.js";

type Tab = "team" | "comments" | "activity" | "notifications";
const date = (value: string) => new Date(value).toLocaleString("ja-JP");
const messageOf = (error: unknown) => error instanceof Error ? error.message : "処理に失敗しました。";

export function CollaborationManager({ api, projectId, role, selectedPath }: { api: StudioApi; projectId: string; role: ProjectMember["role"]; selectedPath?: string | undefined }) {
  const [tab, setTab] = useState<Tab>("team"); const [presence, setPresence] = useState<PresenceUser[]>([]); const [locks, setLocks] = useState<FileLock[]>([]); const [members, setMembers] = useState<ProjectMember[]>([]); const [comments, setComments] = useState<ProjectComment[]>([]); const [activity, setActivity] = useState<ActivityEntry[]>([]); const [notifications, setNotifications] = useState<StudioNotification[]>([]); const [items, setItems] = useState<LogicalItem[]>([]); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const [username, setUsername] = useState(""); const [memberRole, setMemberRole] = useState<Exclude<ProjectMember["role"], "owner">>("editor"); const [commentBody, setCommentBody] = useState(""); const [targetKind, setTargetKind] = useState<"file" | "item">("file"); const [filePath, setFilePath] = useState(selectedPath ?? ""); const [itemId, setItemId] = useState("");
  const canManageMembers = role === "owner" || role === "admin"; const canForceLocks = ["owner", "admin", "manager"].includes(role);
  const reload = async () => { try { const [nextPresence, nextLocks, nextMembers, nextComments, nextActivity, nextNotifications, nextItems] = await Promise.all([api.presence(projectId), api.listLocks(projectId), api.listMembers(projectId), api.listComments(projectId, "open"), api.activity(projectId), api.notifications(), api.listItems(projectId)]); setPresence(nextPresence); setLocks(nextLocks); setMembers(nextMembers); setComments(nextComments); setActivity(nextActivity); setNotifications(nextNotifications); setItems(nextItems); } catch (reason) { setError(messageOf(reason)); } };
  useEffect(() => { void reload(); const fallback = window.setInterval(() => void reload(), 30_000); const realtime = () => void reload(); window.addEventListener("mona-resource-realtime", realtime); return () => { window.clearInterval(fallback); window.removeEventListener("mona-resource-realtime", realtime); }; }, [api, projectId]);
  useEffect(() => { if (selectedPath) setFilePath(selectedPath); }, [selectedPath]);
  const addMember = async () => { if (!username.trim()) return; setBusy(true); setError(""); try { await api.setMember(projectId, username.trim(), memberRole); setUsername(""); await reload(); } catch (reason) { setError(messageOf(reason)); } finally { setBusy(false); } };
  const removeMember = async (member: ProjectMember) => { if (!window.confirm(`${member.displayName} をProjectから削除しますか？`)) return; setBusy(true); try { await api.removeMember(projectId, member.id); await reload(); } catch (reason) { setError(messageOf(reason)); } finally { setBusy(false); } };
  const postComment = async () => { if (!commentBody.trim()) return; setBusy(true); setError(""); try { await api.createComment(projectId, targetKind === "file" ? { body: commentBody.trim(), filePath } : { body: commentBody.trim(), logicalItemId: itemId }); setCommentBody(""); await reload(); } catch (reason) { setError(messageOf(reason)); } finally { setBusy(false); } };
  const forceUnlock = async (lock: FileLock) => { if (!window.confirm(`${lock.displayName} の ${lock.path} Lockを強制解除しますか？`)) return; try { await api.forceReleaseLock(projectId, lock.fileId); await reload(); } catch (reason) { setError(messageOf(reason)); } };
  return <div className="collaboration-manager"><header><div><span className="eyebrow">REALTIME WORKSPACE</span><h2>Collaboration</h2><p>Presence、Soft Lock、コメント、操作履歴、通知をリアルタイムで共有します。</p></div><button className="secondary" onClick={() => void reload()}><RefreshCw />更新</button></header>{error && <div className="build-banner error"><AlertCircle />{error}</div>}
    <nav className="collab-tabs"><button className={tab === "team" ? "active" : ""} onClick={() => setTab("team")}><Users />Team <i>{presence.length}</i></button><button className={tab === "comments" ? "active" : ""} onClick={() => setTab("comments")}><MessageSquare />Comments <i>{comments.length}</i></button><button className={tab === "activity" ? "active" : ""} onClick={() => setTab("activity")}><Activity />Activity</button><button className={tab === "notifications" ? "active" : ""} onClick={() => setTab("notifications")}><Bell />Notifications <i>{notifications.filter((item) => !item.readAt).length}</i></button></nav>
    {tab === "team" && <div className="collab-grid"><section className="collab-card"><header><span>ONLINE NOW</span><small>{presence.length}</small></header><div className="presence-list">{presence.map((person) => <article key={person.id}><Circle /><span><strong>{person.displayName}</strong><small>@{person.username}</small></span><em>online</em></article>)}{!presence.length && <div className="collab-empty">接続中のメンバーはいません。</div>}</div></section><section className="collab-card"><header><span>ACTIVE LOCKS</span><small>{locks.length}</small></header><div className="lock-list">{locks.map((lock) => <article key={lock.fileId}><LockKeyhole /><span><strong>{lock.path}</strong><small>{lock.displayName} · {date(lock.createdAt)}から編集中</small></span>{canForceLocks && <button onClick={() => void forceUnlock(lock)} title="強制解除"><Trash2 /></button>}</article>)}{!locks.length && <div className="collab-empty">編集中のファイルはありません。</div>}</div></section><section className="collab-card members"><header><span>PROJECT MEMBERS</span><small>{members.length}</small></header>{canManageMembers && <div className="member-add"><input value={username} onChange={(event) => setUsername(event.target.value)} placeholder="username" /><select value={memberRole} onChange={(event) => setMemberRole(event.target.value as typeof memberRole)}><option>admin</option><option>manager</option><option>editor</option><option>viewer</option></select><button disabled={busy || !username.trim()} onClick={() => void addMember()}><Plus /></button></div>}<div className="member-list">{members.map((member) => <article key={member.id}><span className="member-avatar">{member.displayName.slice(0, 1).toUpperCase()}</span><span><strong>{member.displayName}</strong><small>@{member.username}</small></span><em>{member.role}</em>{canManageMembers && member.role !== "owner" && <button onClick={() => void removeMember(member)}><Trash2 /></button>}</article>)}</div></section></div>}
    {tab === "comments" && <div className="comments-layout"><section className="comment-compose"><header>NEW COMMENT</header><div className="comment-target"><select value={targetKind} onChange={(event) => setTargetKind(event.target.value as typeof targetKind)}><option value="file">File</option><option value="item">Logical Item</option></select>{targetKind === "file" ? <input value={filePath} onChange={(event) => setFilePath(event.target.value)} placeholder="assets/namespace/..." /> : <select value={itemId} onChange={(event) => setItemId(event.target.value)}><option value="">Itemを選択</option>{items.map((item) => <option key={item.id} value={item.id}>{item.displayName}</option>)}</select>}</div><textarea value={commentBody} onChange={(event) => setCommentBody(event.target.value)} maxLength={4000} rows={5} placeholder="確認してほしい点や修正案を書きます。" /><button className="primary" disabled={busy || !commentBody.trim() || (targetKind === "file" ? !filePath : !itemId)} onClick={() => void postComment()}><MessageSquare />コメントを投稿</button></section><section className="comment-feed">{comments.map((comment) => <article key={comment.id}><header><span className="member-avatar">{comment.displayName.slice(0, 1)}</span><span><strong>{comment.displayName}</strong><small>{date(comment.createdAt)}</small></span><code>{comment.filePath ?? comment.logicalItemName}</code></header><p>{comment.body}</p><button onClick={() => void api.resolveComment(projectId, comment.id, true).then(reload).catch((reason) => setError(messageOf(reason)))}><Check />解決済みにする</button></article>)}{!comments.length && <div className="collab-empty">未解決コメントはありません。</div>}</section></div>}
    {tab === "activity" && <section className="activity-feed">{activity.map((entry) => <article key={entry.id}><span className="activity-dot" /><time>{date(entry.createdAt)}</time><strong>{entry.displayName ?? "System"}</strong><p>{entry.action}</p><code>{String(entry.metadata.path ?? entry.metadata.logicalId ?? entry.targetId ?? "")}</code></article>)}{!activity.length && <div className="collab-empty">Activityはまだありません。</div>}</section>}
    {tab === "notifications" && <section className="notification-feed">{notifications.map((notification) => <button key={notification.id} className={notification.readAt ? "read" : "unread"} onClick={() => !notification.readAt && void api.readNotification(notification.id).then(reload).catch((reason) => setError(messageOf(reason)))}><Bell /><span><strong>{notification.title}</strong><p>{notification.body}</p><small>{notification.projectName ?? "Mona Resource Studio"} · {date(notification.createdAt)}</small></span>{!notification.readAt && <i />}</button>)}{!notifications.length && <div className="collab-empty">通知はありません。</div>}</section>}
  </div>;
}
