import { useEffect, useMemo, useRef, useState } from "react";
import { Eye, EyeOff, FlipHorizontal2, FlipVertical2, Grid3X3, Layers3, PaintBucket, Pencil, Pipette, Plus, Redo2, RotateCw, Save, Scan, Slash, Trash2, Undo2, X } from "lucide-react";
import { MAX_HISTORY, MAX_LAYERS, cloneLayers, colorAt, compositeLayers, createPixels, drawPoint, floodFill, hexToRgba, linePoints, rgbaToHex, setPixel, transformPixels, type PixelLayer, type Rgba } from "@mona/pixel-core";
import type { ProjectFile } from "@mona/shared";
import type { StudioApi } from "./api.js";

type Tool = "pencil" | "eraser" | "fill" | "line" | "eyedropper" | "select";
interface Selection { x0: number; y0: number; x1: number; y1: number; }
interface Draft { baseVersion: number; size: number; activeLayerId: string; saved?: boolean; layers: Array<Omit<PixelLayer, "pixels"> & { pixels: string }>; }

const palette = ["#000000", "#ffffff", "#7f8c8d", "#e74c3c", "#f39c12", "#f1c40f", "#2ecc71", "#1abc9c", "#3498db", "#6c5ce7", "#9b59b6", "#e84393"];
const bytesToBase64 = (bytes: Uint8ClampedArray) => { let binary = ""; for (let offset = 0; offset < bytes.length; offset += 8192) binary += String.fromCharCode(...bytes.subarray(offset, offset + 8192)); return btoa(binary); };
const base64ToBytes = (value: string) => Uint8ClampedArray.from(atob(value), (character) => character.charCodeAt(0));

async function decodePng(blob: Blob): Promise<{ size: number; pixels: Uint8ClampedArray }> {
  const bitmap = await createImageBitmap(blob); if (bitmap.width !== bitmap.height || ![16, 32, 64].includes(bitmap.width)) { bitmap.close(); throw new Error("編集可能な画像サイズは16×16、32×32、64×64です。"); }
  const canvas = document.createElement("canvas"); canvas.width = bitmap.width; canvas.height = bitmap.height; const context = canvas.getContext("2d", { willReadFrequently: true })!; context.drawImage(bitmap, 0, 0); bitmap.close(); return { size: canvas.width, pixels: new Uint8ClampedArray(context.getImageData(0, 0, canvas.width, canvas.height).data) };
}
async function encodePng(pixels: Uint8ClampedArray, size: number): Promise<Blob> {
  const canvas = document.createElement("canvas"); canvas.width = size; canvas.height = size; const context = canvas.getContext("2d")!; context.putImageData(new ImageData(new Uint8ClampedArray(pixels), size, size), 0, 0); return await new Promise((resolve, reject) => canvas.toBlob((blob) => blob ? resolve(blob) : reject(new Error("PNGの生成に失敗しました。")), "image/png"));
}

export function PixelEditor({ api, projectId, file, blob, onSaved, readOnly = false }: { api: StudioApi; projectId: string; file: ProjectFile; blob: Blob; onSaved: () => Promise<void>; readOnly?: boolean }) {
  const canvasRef = useRef<HTMLCanvasElement>(null); const drawing = useRef(false); const start = useRef<[number, number] | null>(null);
  const [size, setSize] = useState(0); const [layers, setLayers] = useState<PixelLayer[]>([]); const [activeLayerId, setActiveLayerId] = useState(""); const [tool, setTool] = useState<Tool>("pencil"); const [color, setColor] = useState("#67e8b2"); const [alpha, setAlpha] = useState(255); const [zoom, setZoom] = useState(12); const [grid, setGrid] = useState(true); const [mirrorX, setMirrorX] = useState(false); const [mirrorY, setMirrorY] = useState(false); const [history, setHistory] = useState<PixelLayer[][]>([]); const [future, setFuture] = useState<PixelLayer[][]>([]); const [selection, setSelection] = useState<Selection | null>(null); const [dirty, setDirty] = useState(false); const [saving, setSaving] = useState(false); const [serverVersion, setServerVersion] = useState(file.version ?? 1); const [message, setMessage] = useState("");
  const draftKey = `mona-pixel-draft:${projectId}:${file.path}`;
  const activeIndex = layers.findIndex((layer) => layer.id === activeLayerId); const composite = useMemo(() => size ? compositeLayers(layers, size) : new Uint8ClampedArray(), [layers, size]);

  useEffect(() => { let cancelled = false; void decodePng(blob).then((decoded) => { if (cancelled) return; let initial: PixelLayer[] = [{ id: crypto.randomUUID(), name: "Imported", visible: true, opacity: 1, pixels: decoded.pixels }]; let active = initial[0]!.id; try { const stored = JSON.parse(localStorage.getItem(draftKey) ?? "null") as Draft | null; if (stored?.baseVersion === (file.version ?? 1) && stored.size === decoded.size) { initial = stored.layers.map((layer) => ({ ...layer, pixels: base64ToBytes(layer.pixels) })); active = stored.activeLayerId; setDirty(!stored.saved); setMessage(stored.saved ? "保存済みレイヤー構成を復元しました。" : "ローカル下書きを復元しました。"); } } catch { localStorage.removeItem(draftKey); } setSize(decoded.size); setZoom(Math.max(6, Math.min(24, Math.floor(480 / decoded.size)))); setLayers(initial); setActiveLayerId(active); setHistory([]); setFuture([]); }).catch((error: unknown) => setMessage(error instanceof Error ? error.message : "PNGを開けません。")); return () => { cancelled = true; }; }, [blob, draftKey, file.version]);

  useEffect(() => { const canvas = canvasRef.current; if (!canvas || !size) return; canvas.width = size; canvas.height = size; canvas.getContext("2d")!.putImageData(new ImageData(new Uint8ClampedArray(composite), size, size), 0, 0); }, [composite, size]);
  useEffect(() => { if (!dirty || !size) return; const timer = window.setTimeout(() => { const draft: Draft = { baseVersion: serverVersion, size, activeLayerId, saved: false, layers: layers.map((layer) => ({ ...layer, pixels: bytesToBase64(layer.pixels) })) }; try { localStorage.setItem(draftKey, JSON.stringify(draft)); setMessage("下書きを端末へ保存しました。"); } catch { setMessage("下書き容量が上限に達しました。サーバーへ保存してください。"); } }, 500); return () => window.clearTimeout(timer); }, [dirty, layers, size, activeLayerId, draftKey, serverVersion]);

  const pushHistory = () => { setHistory((items) => [...items, cloneLayers(layers)].slice(-MAX_HISTORY)); setFuture([]); };
  const updateActive = (mutate: (pixels: Uint8ClampedArray) => void) => { if (readOnly || activeIndex < 0) return; setLayers((items) => items.map((layer, index) => { if (index !== activeIndex) return layer; const pixels = layer.pixels.slice(); mutate(pixels); return { ...layer, pixels }; })); setDirty(true); };
  const pointOf = (event: React.PointerEvent<HTMLCanvasElement>): [number, number] => { const rectangle = event.currentTarget.getBoundingClientRect(); return [Math.max(0, Math.min(size - 1, Math.floor((event.clientX - rectangle.left) / rectangle.width * size))), Math.max(0, Math.min(size - 1, Math.floor((event.clientY - rectangle.top) / rectangle.height * size)))]; };
  const paint = ([x, y]: [number, number]) => updateActive((pixels) => drawPoint(pixels, size, x, y, tool === "eraser" ? [0,0,0,0] : hexToRgba(color, alpha), mirrorX, mirrorY));
  const pointerDown = (event: React.PointerEvent<HTMLCanvasElement>) => { if (readOnly || !size) return; event.currentTarget.setPointerCapture(event.pointerId); const point = pointOf(event); start.current = point; drawing.current = true; if (tool === "select") { setSelection({ x0: point[0], y0: point[1], x1: point[0], y1: point[1] }); return; } if (tool === "eyedropper") { const picked = colorAt(composite, size, point[0], point[1]); setColor(rgbaToHex(picked)); setAlpha(picked[3]); drawing.current = false; return; } pushHistory(); if (tool === "fill") { updateActive((pixels) => floodFill(pixels, size, point[0], point[1], hexToRgba(color, alpha))); drawing.current = false; } else if (tool === "pencil" || tool === "eraser") paint(point); };
  const pointerMove = (event: React.PointerEvent<HTMLCanvasElement>) => { if (!drawing.current) return; const point = pointOf(event); if (tool === "pencil" || tool === "eraser") paint(point); else if (tool === "select" && start.current) setSelection({ x0: start.current[0], y0: start.current[1], x1: point[0], y1: point[1] }); };
  const pointerUp = (event: React.PointerEvent<HTMLCanvasElement>) => { if (!drawing.current) return; const point = pointOf(event); if (tool === "line" && start.current) updateActive((pixels) => { for (const [x, y] of linePoints(start.current![0], start.current![1], point[0], point[1])) drawPoint(pixels, size, x, y, hexToRgba(color, alpha), mirrorX, mirrorY); }); drawing.current = false; start.current = null; };
  const undo = () => { const previous = history.at(-1); if (!previous) return; setFuture((items) => [cloneLayers(layers), ...items]); setLayers(cloneLayers(previous)); setHistory((items) => items.slice(0, -1)); setDirty(true); };
  const redo = () => { const next = future[0]; if (!next) return; setHistory((items) => [...items, cloneLayers(layers)]); setLayers(cloneLayers(next)); setFuture((items) => items.slice(1)); setDirty(true); };
  const transform = (kind: "flip-x" | "flip-y" | "rotate-cw") => { pushHistory(); updateActive((pixels) => pixels.set(transformPixels(pixels, size, kind))); };
  const save = async () => { if (readOnly || !dirty || saving) return; setSaving(true); setMessage("サーバーへ保存しています…"); try { const png = await encodePng(composite, size); const result = await api.saveFile(projectId, file.path, serverVersion, png); const savedDraft: Draft = { baseVersion: result.version, size, activeLayerId, saved: true, layers: layers.map((layer) => ({ ...layer, pixels: bytesToBase64(layer.pixels) })) }; try { localStorage.setItem(draftKey, JSON.stringify(savedDraft)); } catch { /* PNG itself is already persisted on the server. */ } setServerVersion(result.version); setDirty(false); setMessage(`Version ${result.version} として保存しました。`); await onSaved(); } catch (error) { setMessage(error instanceof Error ? error.message : "保存に失敗しました。"); } finally { setSaving(false); } };

  useEffect(() => { const listener = (event: KeyboardEvent) => { if (readOnly) return; if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === "s") { event.preventDefault(); void save(); } if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === "z") { event.preventDefault(); event.shiftKey ? redo() : undo(); } if ((event.key === "Delete" || event.key === "Backspace") && selection && activeIndex >= 0) { event.preventDefault(); pushHistory(); const minX = Math.min(selection.x0, selection.x1); const maxX = Math.max(selection.x0, selection.x1); const minY = Math.min(selection.y0, selection.y1); const maxY = Math.max(selection.y0, selection.y1); updateActive((pixels) => { for (let y = minY; y <= maxY; y += 1) for (let x = minX; x <= maxX; x += 1) setPixel(pixels, size, x, y, [0,0,0,0]); }); } }; window.addEventListener("keydown", listener); return () => window.removeEventListener("keydown", listener); });

  if (!size) return <div className="pixel-loading">{message || "PNGを読み込んでいます…"}</div>;
  const selectionStyle = selection ? { left: `${Math.min(selection.x0, selection.x1) * zoom}px`, top: `${Math.min(selection.y0, selection.y1) * zoom}px`, width: `${(Math.abs(selection.x1 - selection.x0) + 1) * zoom}px`, height: `${(Math.abs(selection.y1 - selection.y0) + 1) * zoom}px` } : undefined;
  return <div className="pixel-editor"><div className="pixel-toolbar"><div className="tool-group">{([["pencil",Pencil,"鉛筆"],["eraser",X,"消しゴム"],["fill",PaintBucket,"塗りつぶし"],["line",Slash,"直線"],["eyedropper",Pipette,"スポイト"],["select",Scan,"選択"]] as const).map(([id,Icon,label]) => <button key={id} className={tool === id ? "active" : ""} title={label} onClick={() => setTool(id)}><Icon /></button>)}</div><div className="tool-group"><button title="Undo" disabled={!history.length} onClick={undo}><Undo2 /></button><button title="Redo" disabled={!future.length} onClick={redo}><Redo2 /></button></div><div className="tool-group"><button className={mirrorX ? "active" : ""} title="左右ミラー" onClick={() => setMirrorX((value) => !value)}><FlipHorizontal2 /></button><button className={mirrorY ? "active" : ""} title="上下ミラー" onClick={() => setMirrorY((value) => !value)}><FlipVertical2 /></button><button title="90度回転" onClick={() => transform("rotate-cw")}><RotateCw /></button><button className={grid ? "active" : ""} title="グリッド" onClick={() => setGrid((value) => !value)}><Grid3X3 /></button></div><div className="zoom-control"><span>{zoom}×</span><input type="range" min="4" max="28" value={zoom} onChange={(event) => setZoom(Number(event.target.value))} /></div><button className="pixel-save" onClick={() => void save()} disabled={!dirty || saving}><Save />{saving ? "保存中" : dirty ? "保存" : "保存済み"}</button></div>
    <div className="pixel-body"><section className="pixel-stage"><div className={`pixel-canvas-wrap ${grid ? "show-grid" : ""}`} style={{ width: size * zoom, height: size * zoom, "--pixel-zoom": `${zoom}px` } as React.CSSProperties}><canvas ref={canvasRef} style={{ width: size * zoom, height: size * zoom }} onPointerDown={pointerDown} onPointerMove={pointerMove} onPointerUp={pointerUp} onPointerCancel={() => { drawing.current = false; }} />{selection && <div className="pixel-selection" style={selectionStyle} />}</div><div className="pixel-status"><span>{size}×{size}</span><span>{tool}</span><span>v{serverVersion}</span>{dirty && <strong>● 未保存</strong>}</div></section>
      <aside className="pixel-sidebar"><section><header>COLOR</header><div className="color-row"><input type="color" value={color} onChange={(event) => setColor(event.target.value)} /><code>{color.toUpperCase()}</code></div><label>Alpha <span>{alpha}</span><input type="range" min="0" max="255" value={alpha} onChange={(event) => setAlpha(Number(event.target.value))} /></label><div className="pixel-palette">{palette.map((entry) => <button key={entry} style={{ background: entry }} className={color === entry ? "active" : ""} onClick={() => setColor(entry)} title={entry} />)}</div></section><section className="layers-panel"><header><span>LAYERS</span><button disabled={layers.length >= MAX_LAYERS} onClick={() => { pushHistory(); const id = crypto.randomUUID(); setLayers((items) => [...items, { id, name: `Layer ${items.length + 1}`, visible: true, opacity: 1, pixels: createPixels(size) }]); setActiveLayerId(id); setDirty(true); }}><Plus /></button></header><div className="layer-list">{[...layers].reverse().map((layer) => <button className={layer.id === activeLayerId ? "active" : ""} key={layer.id} onClick={() => setActiveLayerId(layer.id)}><span onClick={(event) => { event.stopPropagation(); setLayers((items) => items.map((item) => item.id === layer.id ? { ...item, visible: !item.visible } : item)); setDirty(true); }}>{layer.visible ? <Eye /> : <EyeOff />}</span><Layers3 /><strong>{layer.name}</strong><small>{Math.round(layer.opacity * 100)}%</small></button>)}</div><label>Opacity <span>{Math.round((layers[activeIndex]?.opacity ?? 1) * 100)}%</span><input type="range" min="0" max="100" value={Math.round((layers[activeIndex]?.opacity ?? 1) * 100)} onChange={(event) => { const opacity = Number(event.target.value) / 100; setLayers((items) => items.map((layer, index) => index === activeIndex ? { ...layer, opacity } : layer)); setDirty(true); }} /></label><button className="delete-layer" disabled={layers.length <= 1} onClick={() => { if (layers.length <= 1) return; pushHistory(); const next = layers.filter((layer) => layer.id !== activeLayerId); setLayers(next); setActiveLayerId(next[Math.max(0, activeIndex - 1)]!.id); setDirty(true); }}><Trash2 />レイヤーを削除</button></section></aside></div><div className="pixel-message">{message || "変更内容は端末へ自動的に下書き保存されます。"}</div></div>;
}
