import { useEffect, useMemo, useState } from "react";
import { AlertCircle, CheckCircle2, Download, GitPullRequest, PackageCheck, RefreshCcw, Send, XCircle } from "lucide-react";
import type { BuildRecord, ProjectMember, ReleaseRecord, ReviewDetail, ReviewRecord, SnapshotRecord, StudioApi } from "./api.js";

const date = (value: string) => new Date(value).toLocaleString("ja-JP");
const messageOf = (error: unknown) => error instanceof Error ? error.message : "処理に失敗しました。";
const canRequest = (role: ProjectMember["role"]) => ["owner", "admin", "manager", "editor"].includes(role);
const canDecide = (role: ProjectMember["role"]) => ["owner", "admin", "manager"].includes(role);
const canPublish = (role: ProjectMember["role"]) => ["owner", "admin"].includes(role);

export function ReviewManager({ api, projectId, role, userId }: { api: StudioApi; projectId: string; role: ProjectMember["role"]; userId: string }) {
  const [reviews, setReviews] = useState<ReviewRecord[]>([]); const [selected, setSelected] = useState<ReviewDetail | null>(null); const [snapshots, setSnapshots] = useState<SnapshotRecord[]>([]); const [builds, setBuilds] = useState<BuildRecord[]>([]); const [releases, setReleases] = useState<ReleaseRecord[]>([]); const [snapshotId, setSnapshotId] = useState(""); const [title, setTitle] = useState(""); const [description, setDescription] = useState(""); const [note, setNote] = useState(""); const [buildId, setBuildId] = useState(""); const [approvedReviewId, setApprovedReviewId] = useState(""); const [version, setVersion] = useState(""); const [releaseNotes, setReleaseNotes] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const load = async (keepId = selected?.id) => { const [nextReviews, nextSnapshots, nextBuilds, nextReleases] = await Promise.all([api.listReviews(projectId), api.listSnapshots(projectId), api.listBuilds(projectId), api.listReleases(projectId)]); setReviews(nextReviews); setSnapshots(nextSnapshots); setBuilds(nextBuilds); setReleases(nextReleases); if (!snapshotId && nextSnapshots[0]) setSnapshotId(nextSnapshots[0].id); if (keepId) { const match = nextReviews.find((review) => review.id === keepId); setSelected(match ? await api.reviewDetail(projectId, keepId) : null); } };
  useEffect(() => { void load().catch((reason) => setError(messageOf(reason))); }, [projectId]);
  useEffect(() => { const refresh = () => void load().catch(() => undefined); window.addEventListener("mona-resource-realtime", refresh); return () => window.removeEventListener("mona-resource-realtime", refresh); }, [projectId, selected?.id]);
  const approved = useMemo(() => reviews.filter((review) => review.status === "approved"), [reviews]); const selectedApproved = approved.find((review) => review.id === approvedReviewId); const eligibleBuilds = useMemo(() => builds.filter((build) => build.profile === "release" && build.status === "succeeded" && (!selectedApproved || build.snapshotId === selectedApproved.snapshotId)), [builds, selectedApproved?.snapshotId]);
  const inspect = async (review: ReviewRecord) => { setError(""); try { setSelected(await api.reviewDetail(projectId, review.id)); } catch (reason) { setError(messageOf(reason)); } };
  const submit = async () => { if (!snapshotId || !title.trim()) return; setBusy(true); setError(""); try { const created = await api.createReview(projectId, { snapshotId, title: title.trim(), description: description.trim() }); setTitle(""); setDescription(""); setNotice("Reviewを申請しました。"); await load(created.id); } catch (reason) { setError(messageOf(reason)); } finally { setBusy(false); } };
  const decide = async (action: "approve" | "request_changes" | "resubmit" | "cancel") => { if (!selected) return; if (action === "request_changes" && !note.trim()) { setError("修正依頼にはコメントが必要です。"); return; } setBusy(true); setError(""); try { await api.decideReview(projectId, selected.id, action, note.trim(), action === "resubmit" ? snapshotId : undefined); setNote(""); setNotice(action === "approve" ? "Reviewを承認しました。" : action === "request_changes" ? "修正を依頼しました。" : action === "resubmit" ? "修正後SnapshotでReviewを再申請しました。" : "Reviewを取り消しました。"); await load(selected.id); } catch (reason) { setError(messageOf(reason)); } finally { setBusy(false); } };
  const publish = async () => { if (!buildId || !approvedReviewId || !version.trim()) return; setBusy(true); setError(""); try { await api.publishRelease(projectId, { buildId, approvedReviewId, version: version.trim(), releaseNotes: releaseNotes.trim() }); setVersion(""); setReleaseNotes(""); setNotice("不変Releaseを公開しました。"); await load(); } catch (reason) { setError(messageOf(reason)); } finally { setBusy(false); } };
  const download = async (release: ReleaseRecord) => { try { const blob = await api.releaseArtifact(projectId, release.id); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `monaka-resource-${release.version}.zip`; anchor.click(); URL.revokeObjectURL(url); } catch (reason) { setError(messageOf(reason)); } };
  return <div className="review-manager"><header><div><span className="eyebrow">CONTROLLED DELIVERY</span><h2>Review &amp; Release</h2><p>Snapshot差分を承認し、承認対象と一致するRelease Buildだけを公開します。</p></div><button className="tool-button" onClick={() => void load()}><RefreshCcw />更新</button></header>
    {(error || notice) && <div className={`build-banner ${error ? "error" : "success"}`}>{error ? <AlertCircle /> : <CheckCircle2 />}{error || notice}</div>}
    <div className="review-layout"><section className="review-compose"><header>REVIEW REQUEST</header><label>Snapshot<select disabled={!canRequest(role)} value={snapshotId} onChange={(event) => setSnapshotId(event.target.value)}><option value="">選択</option>{snapshots.map((snapshot) => <option key={snapshot.id} value={snapshot.id}>{snapshot.label}</option>)}</select></label><label>Title<input disabled={!canRequest(role)} value={title} onChange={(event) => setTitle(event.target.value)} maxLength={160} /></label><label>Description<textarea disabled={!canRequest(role)} value={description} onChange={(event) => setDescription(event.target.value)} rows={4} /></label><button className="primary" disabled={!canRequest(role) || busy || !snapshotId || !title.trim()} onClick={() => void submit()}><Send />レビュー申請</button></section>
      <section className="review-list"><header>REVIEWS <small>{reviews.length}</small></header>{reviews.length === 0 ? <div className="build-empty"><GitPullRequest />Reviewはありません。</div> : reviews.map((review) => <button key={review.id} className={selected?.id === review.id ? "active" : ""} onClick={() => void inspect(review)}><span className={`review-status ${review.status}`}>{review.status === "approved" ? <CheckCircle2 /> : review.status === "changes_requested" ? <AlertCircle /> : review.status === "cancelled" ? <XCircle /> : <GitPullRequest />}</span><span><strong>{review.title}</strong><small>{review.snapshotLabel} · {review.requestedByName}</small><small>{date(review.createdAt)}</small></span><em>{review.status}</em></button>)}</section></div>
    {selected && <section className="review-detail"><header><span>DIFF · {selected.baseSnapshotLabel ?? "EMPTY"} → {selected.snapshotLabel}</span><div>{Object.entries(selected.summary).map(([key, value]) => <small key={key} className={key}>{key} {value}</small>)}</div></header><div className="review-description"><strong>{selected.title}</strong><p>{selected.description || "説明なし"}</p></div><div className="diff-list">{selected.diff.filter((entry) => entry.status !== "unchanged").length === 0 ? <div className="build-empty">変更はありません。</div> : selected.diff.filter((entry) => entry.status !== "unchanged").map((entry) => <article key={entry.path}><i className={entry.status}>{entry.status[0]?.toUpperCase()}</i><code>{entry.path}</code><span>{entry.before?.size?.toLocaleString() ?? "—"} → {entry.after?.size?.toLocaleString() ?? "—"} bytes</span></article>)}</div><div className="review-actions"><textarea value={note} onChange={(event) => setNote(event.target.value)} placeholder="判定コメント（修正依頼では必須）" rows={2} />{selected.status === "open" && canDecide(role) && selected.requestedBy !== userId && <><button className="primary" onClick={() => void decide("approve")} disabled={busy}><CheckCircle2 />承認</button><button className="danger" onClick={() => void decide("request_changes")} disabled={busy || !note.trim()}><AlertCircle />修正依頼</button></>}{selected.status === "changes_requested" && selected.requestedBy === userId && <button className="primary" onClick={() => void decide("resubmit")} disabled={busy || !snapshotId || snapshotId === selected.snapshotId}><Send />選択中Snapshotで再申請</button>}{["open", "changes_requested"].includes(selected.status) && (selected.requestedBy === userId || canDecide(role)) && <button onClick={() => void decide("cancel")} disabled={busy}><XCircle />取消</button>}</div><div className="review-events">{selected.events.map((event) => <article key={event.id}><time>{date(event.createdAt)}</time><strong>{event.actorName}</strong><code>{event.action}</code><p>{event.note}</p></article>)}</div></section>}
    <div className="release-layout"><section className="review-compose"><header>PUBLISH RELEASE</header><label>Approved review<select disabled={!canPublish(role)} value={approvedReviewId} onChange={(event) => setApprovedReviewId(event.target.value)}><option value="">選択</option>{approved.map((review) => <option key={review.id} value={review.id}>{review.title} · {review.snapshotLabel}</option>)}</select></label><label>Release build<select disabled={!canPublish(role)} value={buildId} onChange={(event) => setBuildId(event.target.value)}><option value="">選択</option>{eligibleBuilds.map((build) => <option key={build.id} value={build.id}>{build.snapshotLabel} · {build.id.slice(0, 8)}</option>)}</select></label><label>Version<input disabled={!canPublish(role)} value={version} onChange={(event) => setVersion(event.target.value)} placeholder="2026.10.05" /></label><label>Release notes<textarea disabled={!canPublish(role)} value={releaseNotes} onChange={(event) => setReleaseNotes(event.target.value)} rows={3} /></label><button className="primary" disabled={!canPublish(role) || busy || !buildId || !approvedReviewId || !version.trim()} onClick={() => void publish()}><PackageCheck />公開</button></section>
      <section className="release-list"><header>IMMUTABLE RELEASES <small>{releases.length}</small></header>{releases.length === 0 ? <div className="build-empty"><PackageCheck />Releaseはありません。</div> : releases.map((release) => <article key={release.id}><span><strong>{release.version}</strong><small>{release.publishedBy} · {date(release.publishedAt)}</small><code>{release.artifactSha256}</code></span><em>{Number(release.artifactSize).toLocaleString()} bytes</em><button onClick={() => void download(release)} title="ダウンロード"><Download /></button></article>)}</section></div>
  </div>;
}
