import { randomBytes } from "node:crypto";
import type { FastifyInstance } from "fastify";
import { z } from "zod";
import { hashToken, requireUser } from "../auth.js";
import type { Database } from "../db/pool.js";
import { AppError } from "../errors.js";
import { requireProjectPermission } from "../policy.js";
import { RealtimeHub } from "../services/realtime.js";

const projectParams = z.object({ projectId: z.string().uuid() });
const idParams = z.object({ projectId: z.string().uuid(), id: z.string().uuid() });
const lockInput = z.object({ path: z.string().min(1).max(1024) });
const tokenInput = z.object({ token: z.string().min(20).max(256) });
const memberInput = z.object({ username: z.string().min(3).max(32), role: z.enum(["admin", "manager", "editor", "viewer"]) });
const commentInput = z.object({ body: z.string().trim().min(1).max(4000), filePath: z.string().min(1).max(1024).optional(), logicalItemId: z.string().uuid().optional(), anchor: z.record(z.string(), z.unknown()).optional() }).refine((value) => Number(Boolean(value.filePath)) + Number(Boolean(value.logicalItemId)) === 1, "filePathまたはlogicalItemIdのどちらか一方が必要です。");
const booleanQuery = z.enum(["true", "false"]).default("false").transform((value) => value === "true");

export async function collaborationRoutes(app: FastifyInstance, db: Database, hub: RealtimeHub): Promise<void> {
  app.post("/projects/:projectId/realtime-ticket", async (request) => { const user = await requireUser(request); const { projectId } = projectParams.parse(request.params); await requireProjectPermission(db, user, projectId, "project.read"); const profile = await db.query<{ username: string; display_name: string }>("SELECT username, display_name FROM users WHERE id = $1 AND disabled_at IS NULL", [user.sub]); if (!profile.rows[0]) throw new AppError(401, "AUTH_REQUIRED", "ユーザーが無効です。"); return { ticket: await hub.issueTicket({ projectId, id: user.sub, username: profile.rows[0].username, displayName: profile.rows[0].display_name, connectedAt: new Date().toISOString() }), expiresIn: 30 }; });
  app.get("/projects/:projectId/realtime", { websocket: true }, (socket, request) => { void (async () => { const { projectId } = projectParams.parse(request.params); const { ticket } = z.object({ ticket: z.string().min(20).max(256) }).parse(request.query); const info = await hub.consumeTicket(ticket); if (!info || info.projectId !== projectId) { socket.close(1008, "Invalid realtime ticket"); return; } await hub.connect(socket, info); })().catch(() => socket.close(1011, "Realtime connection failed")); });
  app.get("/projects/:projectId/presence", async (request) => { const user = await requireUser(request); const { projectId } = projectParams.parse(request.params); await requireProjectPermission(db, user, projectId, "project.read"); return hub.presence(projectId); });

  app.get("/projects/:projectId/locks", async (request) => { const user = await requireUser(request); const { projectId } = projectParams.parse(request.params); await requireProjectPermission(db, user, projectId, "project.read"); await db.query("DELETE FROM file_locks fl USING project_files pf WHERE fl.file_id = pf.id AND pf.project_id = $1 AND fl.expires_at <= now()", [projectId]); return (await db.query(`SELECT fl.file_id AS "fileId", pf.path, fl.owner_id AS "ownerId", u.username, u.display_name AS "displayName", fl.created_at AS "createdAt", fl.expires_at AS "expiresAt" FROM file_locks fl JOIN project_files pf ON pf.id = fl.file_id JOIN users u ON u.id = fl.owner_id WHERE pf.project_id = $1 AND fl.expires_at > now() ORDER BY pf.path`, [projectId])).rows; });
  app.post("/projects/:projectId/locks", async (request, reply) => {
    const user = await requireUser(request); const { projectId } = projectParams.parse(request.params); await requireProjectPermission(db, user, projectId, "file.write"); const body = lockInput.parse(request.body); const client = await db.connect(); const token = randomBytes(32).toString("base64url");
    try { await client.query("BEGIN"); const file = await client.query<{ id: string }>("SELECT id FROM project_files WHERE project_id = $1 AND path = $2 FOR UPDATE", [projectId, body.path]); if (!file.rows[0]) throw new AppError(404, "FILE_NOT_FOUND", "ファイルが見つかりません。"); await client.query("DELETE FROM file_locks WHERE file_id = $1 AND expires_at <= now()", [file.rows[0].id]);
      const active = await client.query<{ owner_id: string; username: string; display_name: string; created_at: string; expires_at: string }>("SELECT fl.owner_id,u.username,u.display_name,fl.created_at,fl.expires_at FROM file_locks fl JOIN users u ON u.id=fl.owner_id WHERE fl.file_id=$1 FOR UPDATE", [file.rows[0].id]); const lock = active.rows[0]; if (lock && lock.owner_id !== user.sub) throw new AppError(423, "FILE_LOCKED", `${lock.display_name} が編集中です。`, { fileId: file.rows[0].id, path: body.path, ownerId: lock.owner_id, username: lock.username, displayName: lock.display_name, createdAt: lock.created_at, expiresAt: lock.expires_at });
      await client.query(`INSERT INTO file_locks(file_id,owner_id,token_hash,expires_at,heartbeat_at) VALUES($1,$2,$3,now()+interval '5 minutes',now()) ON CONFLICT(file_id) DO UPDATE SET owner_id=EXCLUDED.owner_id,token_hash=EXCLUDED.token_hash,expires_at=EXCLUDED.expires_at,heartbeat_at=now()`, [file.rows[0].id, user.sub, hashToken(token)]); await client.query("COMMIT"); await hub.publish(projectId, "lock.changed", { fileId: file.rows[0].id, path: body.path }); reply.code(201); return { fileId: file.rows[0].id, path: body.path, token, expiresAt: new Date(Date.now() + 300_000).toISOString() };
    } catch (error) { await client.query("ROLLBACK"); throw error; } finally { client.release(); }
  });
  app.patch("/projects/:projectId/locks/:id/heartbeat", async (request) => { const user = await requireUser(request); const { projectId, id } = idParams.parse(request.params); await requireProjectPermission(db, user, projectId, "file.write"); const { token } = tokenInput.parse(request.body); const result = await db.query("UPDATE file_locks fl SET heartbeat_at=now(),expires_at=now()+interval '5 minutes' FROM project_files pf WHERE fl.file_id=$1 AND fl.file_id=pf.id AND pf.project_id=$2 AND fl.owner_id=$3 AND fl.token_hash=$4 AND fl.expires_at>now() RETURNING fl.expires_at AS \"expiresAt\"", [id, projectId, user.sub, hashToken(token)]); if (!result.rowCount) throw new AppError(409, "LOCK_LOST", "編集Lockの有効期限が切れました。再度開いてください。"); return result.rows[0]; });
  app.delete("/projects/:projectId/locks/:id", async (request, reply) => { const user = await requireUser(request); const { projectId, id } = idParams.parse(request.params); const { force } = z.object({ force: booleanQuery }).parse(request.query); const body = force ? null : tokenInput.parse(request.body); if (force) await requireProjectPermission(db, user, projectId, "lock.forceRelease"); else await requireProjectPermission(db, user, projectId, "file.write"); const result = await db.query(`DELETE FROM file_locks fl USING project_files pf WHERE fl.file_id=$1 AND fl.file_id=pf.id AND pf.project_id=$2 AND (${force ? "true" : "fl.owner_id=$3 AND fl.token_hash=$4"}) RETURNING pf.path`, force ? [id, projectId] : [id, projectId, user.sub, hashToken(body!.token)]); if (!result.rowCount) throw new AppError(404, "LOCK_NOT_FOUND", "解除できるLockが見つかりません。"); if (force) await db.query("INSERT INTO activity_logs(project_id,actor_id,action,target_type,target_id,metadata,ip,user_agent) VALUES($1,$2,'lock.force_released','file',$3,$4,$5,$6)", [projectId, user.sub, id, JSON.stringify({ path: result.rows[0].path }), request.ip, request.headers["user-agent"] ?? null]); await hub.publish(projectId, "lock.changed", { fileId: id, path: result.rows[0].path }); reply.code(204).send(); });

  app.get("/projects/:projectId/members", async (request) => { const user = await requireUser(request); const { projectId } = projectParams.parse(request.params); await requireProjectPermission(db, user, projectId, "project.read"); return (await db.query(`SELECT u.id,u.username,u.display_name AS "displayName",pm.role,pm.created_at AS "joinedAt" FROM project_members pm JOIN users u ON u.id=pm.user_id WHERE pm.project_id=$1 ORDER BY CASE pm.role WHEN 'owner' THEN 0 WHEN 'admin' THEN 1 WHEN 'manager' THEN 2 WHEN 'editor' THEN 3 ELSE 4 END,u.display_name`, [projectId])).rows; });
  app.put("/projects/:projectId/members", async (request) => { const user = await requireUser(request); const { projectId } = projectParams.parse(request.params); await requireProjectPermission(db, user, projectId, "member.manage"); const body = memberInput.parse(request.body); const target = await db.query<{ id: string }>("SELECT id FROM users WHERE lower(username)=lower($1) AND disabled_at IS NULL", [body.username]); if (!target.rows[0]) throw new AppError(404, "USER_NOT_FOUND", "ユーザーが見つかりません。"); const existing = await db.query<{ role: string }>("SELECT role FROM project_members WHERE project_id=$1 AND user_id=$2", [projectId, target.rows[0].id]); if (existing.rows[0]?.role === "owner") throw new AppError(409, "OWNER_IMMUTABLE", "OwnerのRoleは変更できません。"); await db.query("INSERT INTO project_members(project_id,user_id,role) VALUES($1,$2,$3) ON CONFLICT(project_id,user_id) DO UPDATE SET role=EXCLUDED.role", [projectId, target.rows[0].id, body.role]); await db.query("INSERT INTO notifications(user_id,project_id,type,title,body,metadata) VALUES($1,$2,'member.changed','Projectメンバーに追加されました',$3,$4)", [target.rows[0].id, projectId, `Role: ${body.role}`, JSON.stringify({ role: body.role })]); await db.query("INSERT INTO activity_logs(project_id,actor_id,action,target_type,target_id,metadata,ip,user_agent) VALUES($1,$2,'member.changed','member',$3,$4,$5,$6)", [projectId, user.sub, target.rows[0].id, JSON.stringify({ role: body.role }), request.ip, request.headers["user-agent"] ?? null]); await hub.publish(projectId, "member.changed", { userId: target.rows[0].id, role: body.role }); return { userId: target.rows[0].id, role: body.role }; });
  app.delete("/projects/:projectId/members/:id", async (request, reply) => { const user = await requireUser(request); const { projectId, id } = idParams.parse(request.params); await requireProjectPermission(db, user, projectId, "member.manage"); const removed = await db.query("DELETE FROM project_members WHERE project_id=$1 AND user_id=$2 AND role<>'owner' RETURNING user_id", [projectId, id]); if (!removed.rowCount) throw new AppError(404, "MEMBER_NOT_FOUND", "削除可能なメンバーが見つかりません。"); await db.query("INSERT INTO activity_logs(project_id,actor_id,action,target_type,target_id,ip,user_agent) VALUES($1,$2,'member.removed','member',$3,$4,$5)", [projectId, user.sub, id, request.ip, request.headers["user-agent"] ?? null]); hub.disconnectUser(projectId, id); await hub.publish(projectId, "member.changed", { userId: id, removed: true }); reply.code(204).send(); });

  app.get("/projects/:projectId/comments", async (request) => { const user = await requireUser(request); const { projectId } = projectParams.parse(request.params); await requireProjectPermission(db, user, projectId, "project.read"); const query = z.object({ filePath: z.string().optional(), logicalItemId: z.string().uuid().optional(), resolved: z.enum(["all", "open", "resolved"]).default("open") }).parse(request.query); return (await db.query(`SELECT c.id,c.body,c.anchor,c.file_id AS "fileId",pf.path AS "filePath",c.logical_item_id AS "logicalItemId",li.display_name AS "logicalItemName",c.author_id AS "authorId",u.username,u.display_name AS "displayName",c.resolved_at AS "resolvedAt",c.created_at AS "createdAt" FROM comments c JOIN users u ON u.id=c.author_id LEFT JOIN project_files pf ON pf.id=c.file_id LEFT JOIN logical_items li ON li.id=c.logical_item_id WHERE c.project_id=$1 AND ($2::text IS NULL OR pf.path=$2) AND ($3::uuid IS NULL OR c.logical_item_id=$3) AND ($4='all' OR ($4='open' AND c.resolved_at IS NULL) OR ($4='resolved' AND c.resolved_at IS NOT NULL)) ORDER BY c.created_at DESC LIMIT 200`, [projectId, query.filePath ?? null, query.logicalItemId ?? null, query.resolved])).rows; });
  app.post("/projects/:projectId/comments", async (request, reply) => { const user = await requireUser(request); const { projectId } = projectParams.parse(request.params); await requireProjectPermission(db, user, projectId, "comment.write"); const body = commentInput.parse(request.body); let fileId: string | null = null; if (body.filePath) { const file = await db.query<{ id: string }>("SELECT id FROM project_files WHERE project_id=$1 AND path=$2", [projectId, body.filePath]); if (!file.rows[0]) throw new AppError(404, "FILE_NOT_FOUND", "コメント対象ファイルが見つかりません。"); fileId = file.rows[0].id; } if (body.logicalItemId) { const item = await db.query("SELECT 1 FROM logical_items WHERE project_id=$1 AND id=$2", [projectId, body.logicalItemId]); if (!item.rowCount) throw new AppError(404, "ITEM_NOT_FOUND", "コメント対象Itemが見つかりません。"); }
    const created = await db.query<{ id: string }>("INSERT INTO comments(project_id,file_id,logical_item_id,author_id,body,anchor) VALUES($1,$2,$3,$4,$5,$6) RETURNING id", [projectId, fileId, body.logicalItemId ?? null, user.sub, body.body, body.anchor ? JSON.stringify(body.anchor) : null]); await db.query(`INSERT INTO notifications(user_id,project_id,type,title,body,metadata) SELECT pm.user_id,$1,'comment.created','新しいコメント',$2,$3 FROM project_members pm WHERE pm.project_id=$1 AND pm.user_id<>$4`, [projectId, body.body.slice(0, 240), JSON.stringify({ commentId: created.rows[0]!.id, filePath: body.filePath, logicalItemId: body.logicalItemId }), user.sub]); await db.query("INSERT INTO activity_logs(project_id,actor_id,action,target_type,target_id,metadata,ip,user_agent) VALUES($1,$2,'comment.created','comment',$3,$4,$5,$6)", [projectId, user.sub, created.rows[0]!.id, JSON.stringify({ filePath: body.filePath, logicalItemId: body.logicalItemId }), request.ip, request.headers["user-agent"] ?? null]); await hub.publish(projectId, "comment.created", { commentId: created.rows[0]!.id }); reply.code(201); return { id: created.rows[0]!.id }; });
  app.patch("/projects/:projectId/comments/:id/resolve", async (request) => { const user = await requireUser(request); const { projectId, id } = idParams.parse(request.params); const role = await requireProjectPermission(db, user, projectId, "comment.write"); const comment = await db.query<{ author_id: string }>("SELECT author_id FROM comments WHERE id=$1 AND project_id=$2", [id, projectId]); if (!comment.rows[0]) throw new AppError(404, "COMMENT_NOT_FOUND", "コメントが見つかりません。"); if (comment.rows[0].author_id !== user.sub && !["owner", "admin", "manager"].includes(role)) throw new AppError(403, "COMMENT_RESOLVE_FORBIDDEN", "このコメントを解決する権限がありません。"); const { resolved } = z.object({ resolved: z.boolean() }).parse(request.body); await db.query("UPDATE comments SET resolved_at=$3,resolved_by=$4 WHERE id=$1 AND project_id=$2", [id, projectId, resolved ? new Date() : null, resolved ? user.sub : null]); await db.query("INSERT INTO activity_logs(project_id,actor_id,action,target_type,target_id,metadata,ip,user_agent) VALUES($1,$2,$3,'comment',$4,$5,$6,$7)", [projectId, user.sub, resolved ? "comment.resolved" : "comment.reopened", id, JSON.stringify({ resolved }), request.ip, request.headers["user-agent"] ?? null]); await hub.publish(projectId, "comment.changed", { commentId: id, resolved }); return { id, resolved }; });

  app.get("/projects/:projectId/activity", async (request) => { const user = await requireUser(request); const { projectId } = projectParams.parse(request.params); await requireProjectPermission(db, user, projectId, "project.read"); const { before, limit } = z.object({ before: z.coerce.number().int().positive().optional(), limit: z.coerce.number().int().min(1).max(200).default(100) }).parse(request.query); return (await db.query(`SELECT al.id::text,al.action,al.target_type AS "targetType",al.target_id AS "targetId",al.metadata,al.created_at AS "createdAt",u.username,u.display_name AS "displayName" FROM activity_logs al LEFT JOIN users u ON u.id=al.actor_id WHERE al.project_id=$1 AND ($2::bigint IS NULL OR al.id<$2) ORDER BY al.id DESC LIMIT $3`, [projectId, before ?? null, limit])).rows; });
  app.get("/notifications", async (request) => { const user = await requireUser(request); const { unreadOnly } = z.object({ unreadOnly: booleanQuery }).parse(request.query); return (await db.query(`SELECT n.id,n.project_id AS "projectId",p.name AS "projectName",n.type,n.title,n.body,n.metadata,n.read_at AS "readAt",n.created_at AS "createdAt" FROM notifications n LEFT JOIN projects p ON p.id=n.project_id WHERE n.user_id=$1 AND ($2=false OR n.read_at IS NULL) ORDER BY n.created_at DESC LIMIT 200`, [user.sub, unreadOnly])).rows; });
  app.patch("/notifications/:id/read", async (request) => { const user = await requireUser(request); const { id } = z.object({ id: z.string().uuid() }).parse(request.params); const result = await db.query("UPDATE notifications SET read_at=COALESCE(read_at,now()) WHERE id=$1 AND user_id=$2 RETURNING read_at AS \"readAt\"", [id, user.sub]); if (!result.rowCount) throw new AppError(404, "NOTIFICATION_NOT_FOUND", "通知が見つかりません。"); return result.rows[0]; });
}
